// <auto-generated />
using System;
using ISmart.Repository;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace ISmart.Repository.Migrations
{
    [DbContext(typeof(iSmartDbContext))]
    [Migration("20190607151900__initialModels")]
    partial class _initialModels
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.4-rtm-31024")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("iSmart.Core.Game", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<DateTime>("CreatedDate");

                    b.Property<bool>("IsFree");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Games");

                    b.HasData(
                        new { Id = 1, CreatedDate = new DateTime(2019, 6, 7, 16, 19, 0, 591, DateTimeKind.Local), IsFree = true, Name = "Tennis" },
                        new { Id = 2, CreatedDate = new DateTime(2019, 6, 7, 16, 19, 0, 592, DateTimeKind.Local), IsFree = true, Name = "VolleyBall" }
                    );
                });
#pragma warning restore 612, 618
        }
    }
}
